config/routes.rb
Rails.application.routes.draw do

  get 'casos-de-exito' => 'static_pages#casos', as: 'casos'

  get 'contacto' => 'static_pages#contacto', as: 'contacto'

  get 'distribuidores' => 'static_pages#distribuidores', as: 'distribuidores'

  get 'comprar' => 'static_pages#comprar', as: 'comprar'
  post 'locate_me' => 'static_pages#locate_me'
  root 'static_pages#landing'

  post '/enviar_contacto' => 'static_pages#enviar_contacto', as: 'enviar_contacto'
  post '/enviar_distribuidor' => 'static_pages#enviar_distribuidor', as: 'enviar_distribuidor'

  get 'admin' => 'admin#index'
  scope 'admin', path_names: { new: 'nuevo', edit: 'editar' } do

    devise_for :users, :controllers => {:sessions => "sessions"} , path: "auth", path_names: { sign_in: 'login', sign_out: 'logout' }

    get 'contacto' => 'admin#contact', as: 'contact'
    patch 'contacto' => 'admin#contact'
    delete 'contacto' => 'admin#pref_del'

    get 'paypal' => 'admin#paypal', as: 'paypal'
    patch 'paypal' => 'admin#paypal'

    resources :users, path: 'usuarios', except: :show

    resources :announcements, path: 'anuncios', except: :show

    resources :cases, path: 'casos-de-exito'
    resources :dealers, path: 'distribuidores', except: :show

  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def initialize
    super
    if Preference.first.nil?
      p = Preference.new
      p.save
    end
  end

  def landing
    @case = Case.first
    Case.all.each do |c|
      if c.featured
        @case = c
      end
    end
  end

  def locate_me

    lat = params[:lat]
    lng = params[:lng]

    @ajax_dealers = Dealer.all.sort_by do |d|
      diss = haversine_distance( lat.to_d, lng.to_d, d.latitude, d.longitude)
      puts diss[:km]
      d.km = diss[:km]
      diss[:km]
    end

    render  'lista_distribuidores', :layout => false

  end

  def casos
    @cases = Case.all
  end

  def contacto
    @prefs = Preference.first
    @contact = Contact.new
  end

  def enviar_contacto
    @prefs = Preference.first
    @contact = Contact.new(params[:contact])
    @contact.request = request

    if @contact.deliver
      render partial: 'distribuidores_contacto_success'
    else
      render partial: 'contacto_contacto'
    end
  end

  def distribuidores
    @dealer_contact = DealerContact.new
  end

  def enviar_distribuidor
    @dealer_contact = DealerContact.new(params[:dealer_contact])
    @dealer_contact.request = request

    if @dealer_contact.deliver
      render partial: 'distribuidores_contacto_success'
    else
      render partial: 'distribuidores_contacto'
    end

  end

  def comprar
    @dealers = Dealer.all
  end


  private
    def haversine_distance( lat1, lon1, lat2, lon2 )

    rad_per_deg = 0.017453293
    rmiles  = 3956           # radius of the great circle in miles
    rkm     = 6371           # radius in kilometers, some algorithms use 6367
    rfeet   = rmiles * 5282  # radius in feet
    rmeters = rkm * 1000

    dlon = lon2 - lon1
    dlat = lat2 - lat1

    dlon_rad = dlon * rad_per_deg
    dlat_rad = dlat * rad_per_deg

    lat1_rad = lat1 * rad_per_deg
    lon1_rad = lon1 * rad_per_deg

    lat2_rad = lat2 * rad_per_deg
    lon2_rad = lon2 * rad_per_deg

    a = (Math.sin(dlat_rad/2))**2 + Math.cos(lat1_rad) *
         Math.cos(lat2_rad) * (Math.sin(dlon_rad/2))**2
    c = 2 * Math.atan2( Math.sqrt(a), Math.sqrt(1-a))

    dMi     = nil #rmiles * c      # delta between the two points in miles
    dKm     = rkm * c         # delta in kilometers
    dFeet   = nil #rfeet * c       # delta in feet
    dMeters = nil #rmeters * c     # delta in meters

    { :mi => dMi, :km => dKm, :ft => dFeet, :m => dMeters }
  end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/_contacto_contacto.html.erb
  <div class="titulo">Envíanos un mensaje.</div>
  <%= form_for @contact, :url => enviar_contacto_path, :method => :post, remote: true do |f| %>
    <%= full_field_batukeira f, :name, "Nombre" %>
    <%= full_field_batukeira f, :email, "Correo electrónico" %>

    <%= full_field_batukeira f, :subject, "Asunto" %>
    <%= full_text_batukeira f, :message, "Mensaje" %>

    <%= f.hidden_field :nickname %>
    <%= f.button :Enviar, class: 'boton' %>
  <% end %>

app/views/static_pages/_distribuidores_contacto.html.erb
<div class="titulo">Llena este formulario</div>
<%= form_for @dealer_contact, :url => enviar_distribuidor_path, :method => :post, remote: true do |f| %>
    <%= full_field_batukeira f, :name, "Nombre" %>
    <%= full_field_batukeira f, :email, "Correo electrónico" %>
    <%= full_field_batukeira f, :telephone, "Teléfono" %>
    <%= full_field_batukeira f, :telephone2, "Teléfono 2 (opcional)" %>
    <%= full_text_batukeira f, :address, "Dirección" %>
    <%= f.hidden_field :nickname %>
    <%= f.button :Enviar, class: 'boton' %>
  <% end %>

app/views/static_pages/_distribuidores_contacto_success.html.erb
<div class="titulo">¡Gracias!</div>

app/views/static_pages/casos.html.erb
<section class="casos-de-exito">
<div class="fondo"></div>
<h1 class="titulo">
  Casos de Éxito
</h1>
<h5 class="descripcion">
  Ve los resultados que personas como tú han obtenido con Batukeira®.
</h5>
</section>

<section class="casos-listado">

<% @cases.each_with_index do |c,i| %>
  <div class="celda">
    <div class="datos <%= "solo-datos".html_safe %>">
      <div class="centrado-vertical">
        <div class="nombre"><%= c.title %></div>

        <div class="atributo">
          <% if !c.weight_before.nil? %>
            <span>Peso inicial:</span> <%= number_with_precision(c.weight_before, :precision => 2) %> Kg
          <% end %>
          <% if !c.weight_after.nil? %>
            <span>Peso inicial:</span> <%= number_with_precision(c.weight_after, :precision => 2) %>  Kg
          <% end %>
        </div>

        <div class="atributo">
          <% if !c.waist_before.nil? %>
            <span>Peso inicial:</span> <%= number_with_precision(c.waist_before, :precision => 2) %> cm
          <% end %>
          <% if !c.waist_after.nil? %>
            <span>Peso inicial:</span> <%= number_with_precision(c.waist_after, :precision => 2) %>  cm
          <% end %>
        </div>

        <br>

        <% if !c.eleapsed_time.empty? %>
          <div class="atributo"><span>Tiempo invertido:</span><%= c.eleapsed_time %></div>
        <% end %>

        <% if !c.product_used.empty? %>
          <div class="atributo"><span>Producto utilizado:</span><%= c.product_used %></div>
        <% end %>

        <div class="descripcion"><%= c.description %></div>
      </div>
    </div>
    <div class="galeria">
      <div class="gallery-top-<%= i %> swiper-container ">
        <div class="swiper-wrapper">
          <% c.photos.each do |photo| %>
            <div class="swiper-slide" style="background-image:url(<%=photo.photo_file.url(:thumb)%>)">
              <div class="detalles">
                <% if !photo.month.nil? && !photo.year.nil? %>
                  <%= num_to_month(photo.month) %> <%= photo.year %>
                <% end %>
                <% if !photo.weight.nil? %>
                   Peso: <%= number_with_precision(photo.weight, :precision => 2) %> Kg
                <% end %>
              </div>
            </div>
          <% end %>

        </div>
        <div class="swiper-button-next next-<%= i %> swiper-button-white"></div>
        <div class="swiper-button-prev prev-<%= i %> swiper-button-white"></div>
      </div>

      <script>
      var galleryTop = new Swiper('.gallery-top-<%= i %>', {
          nextButton: '.next-<%= i %>',
          prevButton: '.prev-<%= i %>',
          spaceBetween: 0,
          speed:500,
          autoplay:3000,
          slidesPerView:2,
          keyboardControl: true
        });
      </script>
    </div>
  </div>
<% end %>

</section>

<section class="batukeria-te-ayudo">
  <div class="titulo">¿Batukeira te ayudó a ti? <%= link_to("Envíanos tu caso", contacto_path) %></div>
</section>

app/views/static_pages/comprar.html.erb
<section class="baja-de-peso" style="height: 600px">
  <div class="logo"></div>
  <div class="centrado-vertical">
    <h1 class="titulo animated fadeInLeft">Productos <br> Batukeira</h1>
    <div class="descripcion animated fadeInLeft">Compra en línea o encuentra tu distribuidor <br> más cercano.</div>
  </div>
</section>

<section class="pago-en-linea">
  <h2 class="title">Pago en línea</h2>
  <% if Preference.first.paypal %>
  <%= Preference.first.paypal.html_safe %>
  <% end %>
</section>

<div id="geolocation"></div>
<section class="distribuidores-cerca">
<div class="fondo"></div>
<h1 class="titulo">
  Distribuidores cerca de ti.
</h1>
<h5 class="descripcion">
  Adquiere y empieza a gozar los beneficios de los <br> productos Batukeira®.
</h5>
</section>



<section class="todos-los-distribuidores">
  <div class="titulo">Estamos tratando de localizarte...</div>
</section>

<section class="distribuidores-listado u-cf">

<% @dealers.each do |d| %>
  <div class="celda">
    <div class="centrado-vertical">
      <div class="nombre"><%= d.name %></div>
      <div class="direccion"><%= d.hidden_address ? d.visible_address : d.address %></div>
      <% if d.email.present? %>
        <a href="mailto:<%= d.email %>?Subject=Batukeira" target="_top" class="email"><%= d.email %></a>
      <% end %>
      <a href="tel:<%= d.telephone %>" class="telefono"><%= d.telephone %></a>
      <% if d.telephone2.present? %>
        <a href="tel:<%= d.telephone2 %>" class="telefono"><%= d.telephone2 %></a>
      <% end %>
    </div>
  </div>
<% end %>

</section>


<!-- distribuidores aquí -->

app/views/static_pages/contacto.html.erb
<% content_for :fixed_nav, 'scrolled fixed' %>
<section class="row contacto">
  <div class="fondo"></div>
  <div class="info">
    <div class="centrado-vertical">
      <h1 class="titulo">Contáctanos</h1>


    <% if @prefs.facebook.present? %>
      <div class="texto">Facebook:</div>
      <ul class="lista">
        <li><a href="<%= @prefs.facebook %>"><%= @prefs.facebook %></a></li>
      </ul>
    <% end %>

    <% if @prefs.twitter.present? %>
      <div class="texto">Twitter:</div>
      <ul class="lista">
        <li><a href="<%= @prefs.twitter %>"><%= @prefs.twitter %></a></li>
      </ul>
    <% end %>

    <% if @prefs.email.present? %>
      <div class="texto">Correo electrónico:</div>
      <ul class="lista">
        <li><a href="mailto:<%= @prefs.email %>?Subject=Batukeira" target="_top" class="email"><%= @prefs.email %></a></li>
      </ul>
    <% end %>

    <% if @prefs.telephone.present? || @prefs.telephone2.present? %>
      <div class="texto whatsapp">Teléfono (Whats App)</div>
      <ul class="lista">
       <% if @prefs.telephone.present? %>
        <li><a href="tel:<%= @prefs.telephone %>" class="telefono"><%= @prefs.telephone %></a></li>
       <% end %>
      <% if @prefs.telephone2.present? %>
        <li><a href="tel:<%= @prefs.telephone2 %>" class="telefono"><%= @prefs.telephone2 %></a></li>
       <% end %>
      </ul>
    <% end %>
    </div>
  </div>

  <div class="forma">
    <div id="contact-form" class="centrado-vertical-forma">
      <%= render "contacto_contacto" %>
    </div>
  </div>

</section>

app/views/static_pages/distribuidores.html.erb
<section class="vuelvete">
<svg class="curva" preserveAspectRatio="none" version="1.1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 10 10">
  <path d="M 8 10 H 0 L -1 2 Q 0 10 8 10"></path>
</svg>
<div class="fondo"></div>
<div class="centrado-vertical">
  <h1 class="titulo">Vuélvete un distribuidor <br> Batukeira®</h1>
  <div class="descripcion">Expande tu negocio y ayuda a las personas a alcanzar sus metas.</div>
</div>
</section>
<section class="row beneficios">
<!-- <h2 class="titulo">Beneficios</h2> -->
<div class="row">
  <div class="six columns">
      <div class="titulo">Grandes márgenes de ganancia</div>
          <div class="descripcion">Tu inversión por grandes retornos.</div>
  </div>
  <div class="six columns">
      <div class="titulo">Los clientes llegan solos</div>
      <div class="descripcion">Precencia en nuestro sitio web para que tus clientes te encuentren.</div>
  </div>
</div>
<div class="row">
    <div class="titulo">Negocio sencillo en todo el país.</div>
    <div class="descripcion">Ordena por teléfono y utiliza cualquier forma de pago.</div>

</div>
</section>
<section class="row como-convertirse">
  <div class="fondo"></div>
  <div class="row">
    <h2 class="titulo">¿Cómo convertirse en distribuidor?</h2>
  </div>
  <div class="row columnas">
    <div class="four columns">
      <div class="centrado-vertical">
        <div class="texto">
          Llena el formulario.
        </div>
        <div class="descripcion">
         Para ser registrado como distribuidor.
        </div>
      </div>
    </div>
    <div class="four columns">
      <div class="centrado-vertical">
        <div class="texto">
          Realiza tus pedidos.
        </div>
        <div class="descripcion">
          Solicita todo el material que vas a vender.
        </div>
      </div>
    </div>
    <div class="four columns">
      <div class="centrado-vertical">
        <div class="texto">
          Genera utilidad.
        </div>
        <div class="descripcion">
          Expande tu negocio al vender productos Batukeira®.
        </div>
      </div>
    </div>
  </div>
</section>

<section id="contact-form" class="formulario">
  <%= render "distribuidores_contacto" %>
</section>



<section class="row preguntas-frecuentes">
  <div class="titulo">Preguntas Frecuentes</div>
</section>

<div class="pregunta">
¿Los pedidos se envían a mi domicilio?

  <div class="respuesta">
Los pedidos pueden recogerse en Naucalpan, Estado de México o pueden enviarse a su domicilio (más costos de envío).
  </div>
</div>

<div class="pregunta">
¿Es necesario comprar una cantidad mínima mensual?
  <div class="respuesta">
  Sí, un mínimo de 10 piezas mensuales.
  </div>
</div>

<div class="pregunta">
¿Hay que pagar una suscripción?

  <div class="respuesta">
  Sí, tiene un costo de $500 MXN.
  </div>
</div>
<div class="pregunta">

¿Tienen permiso para distribuirlas?
  <div class="respuesta">
Sí, el producto está autorizado por la Secretaría de Saludo y la Cofepris.

  </div>
</div>
<div class="pregunta">
¿Puedo comprarle a alguien más o debe ser directamente a ustedes?
  <div class="respuesta">
Nosotros somos los únicos distribuidores nacionales e internacionales.

  </div>
</div>
<div class="pregunta">
¿El pago se realiza antes o después de recibir el producto?
  <div class="respuesta">
Se realiza antes de recibir el producto, el envío se hace después de efectuar el pago.
  </div>
</div>
<div class="pregunta">
¿Hay algún tipo de crédito, mensualidades, abonos, etcétera?

  <div class="respuesta">
No, por ahora solo aceptamos pagos de contado.
  </div>
</div>
<div class="pregunta">

¿En cuánto tiempo llegará mi pedido?
  <div class="respuesta">
En un tiempo máximo de 5 días hábiles.
  </div>
</div>

<div class="pregunta">
¿Hay más distribuidores donde estaré yo?
  <div class="respuesta">
Buscamos que haya máximo 3 distribuidores por ciudad.</div>
</div>

app/views/static_pages/lista_distribuidores.html.erb
<% @ajax_dealers.each_with_index do |d,i| %>
  <div class="celda animated fadeIn" style="animation-delay:<%= i * 0.2 %>s">
    <div class="centrado-vertical">
      <div class="nombre"><%= d.name %><span>- <%= d.km.round(2) %> Km</span></div>
      <div class="direccion"><%= d.hidden_address ? d.visible_address : d.address %></div>
      <% if !d.email.empty? %>
        <a href="mailto:<%= d.email %>?Subject=Batukeira" target="_top" class="email"><%= d.email %></a>
      <% end %>
      <a href="tel:<%= d.telephone %>" class="telefono"><%= d.telephone %></a>
      <% if !d.telephone2.empty? %>
        <a href="tel:<%= d.telephone2 %>" class="telefono"><%= d.telephone2 %></a>
      <% end %>
    </div>
  </div>
<% end %>