config/routes.rb
Rails.application.routes.draw do

  get 'casos-de-exito' => 'static_pages#casos', as: 'casos'

  get 'contacto' => 'static_pages#contacto', as: 'contacto'

  get 'distribuidores' => 'static_pages#distribuidores', as: 'distribuidores'

  get 'comprar' => 'static_pages#comprar', as: 'comprar'
  post 'locate_me' => 'static_pages#locate_me'
  root 'static_pages#landing'

  post '/enviar_contacto' => 'static_pages#enviar_contacto', as: 'enviar_contacto'
  post '/enviar_distribuidor' => 'static_pages#enviar_distribuidor', as: 'enviar_distribuidor'

  get 'admin' => 'admin#index'
  scope 'admin', path_names: { new: 'nuevo', edit: 'editar' } do

    devise_for :users, :controllers => {:sessions => "sessions"} , path: "auth", path_names: { sign_in: 'login', sign_out: 'logout' }

    get 'contacto' => 'admin#contact', as: 'contact'
    patch 'contacto' => 'admin#contact'
    delete 'contacto' => 'admin#pref_del'

    get 'paypal' => 'admin#paypal', as: 'paypal'
    patch 'paypal' => 'admin#paypal'

    resources :users, path: 'usuarios', except: :show

    resources :announcements, path: 'anuncios', except: :show

    resources :cases, path: 'casos-de-exito'
    resources :dealers, path: 'distribuidores', except: :show

  end

end

app/models/announcement.rb
class Announcement < ActiveRecord::Base

  before_save :only_one_featured

  has_attached_file :image,
  :styles => {
    :thumb => "400x400>" },
  :convert_options => {
    :thumb => "-quality 95 -strip" }

  validates_attachment :image, :presence => true,
  :content_type => { :content_type => ["image/jpeg", "image/gif", "image/png"] }


  private
    def only_one_featured
      if self.featured
        Announcement.update_all(featured: false)
        self.featured = true
      end
    end

end

app/controllers/announcements_controller.rb
class AnnouncementsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_case, only: [:show, :edit, :update, :destroy]

  layout 'admin'

  # GET /cases
  def index
    @cases = Announcement.all
  end

  # GET /cases/1
  def show
  end

  # GET /cases/new
  def new
    @case = Announcement.new
  end

  # GET /cases/1/edit
  def edit
  end

  # POST /cases
  def create
    @case = Announcement.new(case_params)

    if @case.save
      flash[:success] = 'Se han guardado los cambios.'
      redirect_to announcements_path
    else
      render :new
    end
  end

  # PATCH/PUT /cases/1
  def update


    if @case.update(case_params)
      flash[:success] = 'Se han guardado los cambios.'
      redirect_to announcements_path
    else
      render :edit
    end
  end

  # DELETE /cases/1
  def destroy
    flash[:warning] = "Se ha destruído el anuncio: #{@case.title}"
    @case.destroy
    respond_to do |format|
      format.html { redirect_to announcements_url }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_case
      @case = Announcement.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def case_params
      params.require(:announcement).permit(:title,:link,:image,:validity,:featured)
    end

end

app/views/announcements/_form.html.erb
<%# Form fields %>
<%= form_for(@case, :html => { :multipart => true }) do |f| %>
  <% if @case.errors.any? %>
    <div class="error-explanation-header">
      <%= pluralize(@case.errors.count, "error impidió", "errores impidieron") %> que se guardaran los cambios.
    </div>
<% end %>

<%# Título y descripción %>
<div class="row">
  <%= full_field(f,:title,'Titulo del anuncio' ,'Nueva promoción de descuentos...') %>
  <%= full_field(f,:link,'Link' ,'http://...') %>
  Imagen de anuncio:
  <%= f.file_field :image, class: "form-control" %>
  <%= f.label :featured, class:'field-options-wrapper' do %>
      <%= f.check_box :featured %>Anuncio Actual
  <% end %>
</div>

<div class="row">
  <div class="six columns">
    <%= link_to "Salir sin guardar", cases_path, class: 'c4-button-secondary u-full-width'  %>
  </div>

  <div class="six columns">
    <%= f.submit "Guardar", class: 'c4-button-primary u-full-width' %>
  </div>
</div>

<% end %>

app/views/announcements/edit.html.erb
<%= content_for :title, "Editar" %>
<% content_for :header_content do %>
<h1><b>Editar anuncio:</b> <%= @case.title %></h1>
<% end %>
<%= render 'form' %>

app/views/announcements/index.html.erb
<%= content_for :title, "Anuncios" %>

<% content_for :header_content do %>
<h1><strong>Todos los Anuncios</strong></h1>
<% end %>

<%= link_to new_announcement_path, class: 'c4-button-success' do %>
  Agregar nuevo
<% end %>
<div class="c4-list-collection">
  <% if @cases.empty? %>
    <div class="no-content">
      <span class="icon-error"></span>
      <div>Sin contenido</div>
    </div>
  <% end %>
  <% @cases.each do |c| %>
  <div class="c4-list-cell">
    <div class="row top-row">
      <div class="nine columns">
        <div class="title">
          <%= '<span class="icon-view_carousel"></span>'.html_safe if c.featured %>
          <%= c.title %>
        </div>
      </div>
      <div class="three columns">
        <div class="date">
          <%= c.created_at.strftime('%d/%m/%Y') %>
        </div>
      </div>
    </div>
    <div class="row">
    <div class="four columns">
      <div class="thumbnail" style="background-image: url(<%= c.image.url(:thumb) %>)"></div>
    </div>
      <div class="eight columns">
        <div class="description">
          <%= c.link %>
        </div>
        <div class="row buttons-container">
        <%= link_to edit_announcement_path(c), class:'c4-button-primary' do %>
          <span class="icon-edit"></span>
        <% end %>
          <%= link_to c, method: :delete, data: { confirm: 'Esta acción no puede deshacerse. ¿Está seguro que desea borrar este elemento?'}, class:'c4-button-warning' do %>
            <span class="icon-delete"></span>
          <% end %>
        </div>
      </div>
    </div>
  </div>
  <% end %>
</div>

app/views/announcements/new.html.erb
<%= content_for :title, "Nuevo" %>
<% content_for :header_content do %>
<h1><b>Nuevo Anuncio</b></h1>
<% end %>
<%= render 'form' %>