config/routes.rb
Rails.application.routes.draw do

  get 'casos-de-exito' => 'static_pages#casos', as: 'casos'

  get 'contacto' => 'static_pages#contacto', as: 'contacto'

  get 'distribuidores' => 'static_pages#distribuidores', as: 'distribuidores'

  get 'comprar' => 'static_pages#comprar', as: 'comprar'
  post 'locate_me' => 'static_pages#locate_me'
  root 'static_pages#landing'

  post '/enviar_contacto' => 'static_pages#enviar_contacto', as: 'enviar_contacto'
  post '/enviar_distribuidor' => 'static_pages#enviar_distribuidor', as: 'enviar_distribuidor'

  get 'admin' => 'admin#index'
  scope 'admin', path_names: { new: 'nuevo', edit: 'editar' } do

    devise_for :users, :controllers => {:sessions => "sessions"} , path: "auth", path_names: { sign_in: 'login', sign_out: 'logout' }

    get 'contacto' => 'admin#contact', as: 'contact'
    patch 'contacto' => 'admin#contact'
    delete 'contacto' => 'admin#pref_del'

    get 'paypal' => 'admin#paypal', as: 'paypal'
    patch 'paypal' => 'admin#paypal'

    resources :users, path: 'usuarios', except: :show

    resources :announcements, path: 'anuncios', except: :show

    resources :cases, path: 'casos-de-exito'
    resources :dealers, path: 'distribuidores', except: :show

  end

end

app/models/dealer.rb
class Dealer < ActiveRecord::Base

  attr_accessor :km
  validates :name, presence: true
  validates :address, presence: true
  validates :telephone, format: { with: /\A[]\d\(\)\+\s]+\z/i}
  validates :telephone2, format: { with: /\A[]\d\(\)\+\s]+\z/i }, :allow_blank => true
   validates :email, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i }, :allow_blank => true

end

app/controllers/dealers_controller.rb
class DealersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_dealer, only: [:show, :edit, :update, :destroy]
  layout 'admin'
  # GET /dealers
  # GET /dealers.json
  def index
    @dealers = Dealer.all
  end

  # GET /dealers/new
  def new
    @dealer = Dealer.new
  end

  # GET /dealers/1/edit
  def edit
  end

  # POST /dealers
  # POST /dealers.json
  def create
    @dealer = Dealer.new(dealer_params)
    respond_to do |format|
      if @dealer.save
        flash[:success] = 'Se han guardado los cambios.'
        format.html { redirect_to dealers_url }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /dealers/1
  # PATCH/PUT /dealers/1.json
  def update
    respond_to do |format|
      if @dealer.update(dealer_params)
        flash[:success] = 'Se han guardado los cambios.'
        format.html { redirect_to dealers_url }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /dealers/1
  # DELETE /dealers/1.json
  def destroy
    @dealer.destroy
    respond_to do |format|
      flash[:warning] = "Se ha destruído el distribuidor: #{@dealer.name}"
      format.html { redirect_to dealers_url }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dealer
      @dealer = Dealer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def dealer_params
      params.require(:dealer).permit(:name, :telephone, :telephone2, :email, :address, :latitude, :longitude, :hidden_telephone, :hidden_telephone2, :hidden_email, :hidden_address, :visible_address)
    end
end

app/helpers/dealers_helper.rb
module DealersHelper
  def hidden_icon(hidden)
    if hidden
      "<span class='icon-visibility_off'></span>".html_safe
    end
  end
end

app/views/dealers/_form.html.erb
<%# Form fields %>
<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?libraries=places&language=es"></script>
<%= javascript_include_tag 'location-picker'  %>

<%= form_for(@dealer) do |f| %>
  <% if @dealer.errors.any? %>
    <div class="error-explanation-header">
      <%= pluralize(@dealer.errors.count, "error impidió", "errores impidieron") %> que se guardaran los cambios.
    </div>
<% end %>

<%# Nombre y dirección %>

<div class="row">
 <%= full_field(f,:name,'Nombre del distribuidor' ,'Eduardo Chávez / Farmacias Pablito') %>
</div>
<div id="map-location-picker">
</div>
<div class="row">
  <%= full_field(f,:address,'Dirección' ,'Calle Zaragoza esq. 5 de Mayo Zona centro Monterrey, N. L., México CP 64000' ) %>
  <%= f.label :hidden_address, class:'field-options-wrapper' do %>
        <%= f.check_box :hidden_address %>Esconder de la página principal
      <% end %>

  <%= full_field(f,:visible_address,'Dirección Visible' ,'Atizapán' ) %>

</div>

<%# Latitud y longitud escondidos %>
<%= f.hidden_field :latitude %>
<%= f.hidden_field :longitude %>

<hr class="c4-mini">

<%# Teléfonos %>
<div class="row">
  <div class="six columns">
      <%= full_field(f,:telephone,'Teléfono','') %>
      <%= f.label :hidden_telephone, class:'field-options-wrapper' do %>
        <%= f.check_box :hidden_telephone %>Esconder de la página principal
      <% end %>
  </div>
  <div class="six columns">
      <%= full_field(f,:telephone2,'Teléfono secundario (opcional)','') %>
      <%= f.label :hidden_telephone2, class:'field-options-wrapper' do %>
        <%= f.check_box :hidden_telephone2 %>Esconder de la página principal
      <% end %>
  </div>
</div>

<hr class="c4-mini">

<%# Email %>
<div class="row">
    <%= full_field(f,:email,'Correo electrónico','ejemplo@ejemplo.com') %>
    <%= f.label :hidden_email, class:'field-options-wrapper' do %>
      <%= f.check_box :hidden_email %>Esconder de la página principal
    <% end %>
</div>

<hr>


<div class="row">
  <div class="six columns">
    <%= link_to "Salir sin guardar", dealers_path, class: 'c4-button-secondary u-full-width'  %>
  </div>

  <div class="six columns">
    <%= f.submit "Guardar", class: 'c4-button-primary u-full-width' %>
  </div>
</div>

<% end %>

app/views/dealers/edit.html.erb
<%= content_for :title, "Editar" %>
<% content_for :header_content do %>
<h1><b>Editar distribuidor:</b> <%= @dealer.name %></h1>
<% end %>
<%= render 'form' %>

app/views/dealers/index.html.erb
<%= content_for :title, "Distribuidores" %>

<% content_for :header_content do %>
<h1><strong>Todos los distribuidores</strong></h1>
<% end %>

<%= link_to new_dealer_path, id:'new-case-button', class: 'c4-button-success' do %>
  Agregar nuevo
<% end %>

<div class="c4-list-collection">
  <% if @dealers.empty? %>
    <div class="no-content">
      <span class="icon-error"></span>
      <div>Sin contenido</div>
    </div>
  <% end %>
  <% @dealers.each do |c| %>
  <div class="c4-list-cell">
    <div class="row header">
      <div class="nine columns">
        <div class="title">
          <%= c.name %>
        </div>
      </div>
      <div class="three columns">
        <div class="date">
          <%= c.created_at.strftime('%d/%m/%Y') %>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="twelve columns">
        <div class="properties">
          <ul>
            <li><%= hidden_icon(c.hidden_address) %><strong>Dirección</strong>: <%= c.address %></li>
            <li><%= hidden_icon(c.hidden_telephone) %><strong>Teléfono</strong>: <%= c.telephone %> </li>
            <li><%= hidden_icon(c.hidden_telephone2) %><strong>Teléfono 2</strong>: <%= c.telephone2 %> </li>
            <li><%= hidden_icon(c.hidden_email) %><strong>Correo electrónico</strong>: <%= c.email %> </li>
          </ul>
        </div>
        <div class="row buttons-container">
        <%= link_to edit_dealer_path(c), class:'c4-button-primary' do %>
          <span class="icon-edit"></span>
        <% end %>
          <%= link_to c, method: :delete, data: { confirm: 'Esta acción no puede deshacerse. ¿Está seguro que desea borrar este elemento?'}, class:'c4-button-warning' do %>
            <span class="icon-delete"></span>
          <% end %>
        </div>
      </div>
    </div>
  </div>
  <% end %>
  <div class="c4-spacer"></div>
</div>

app/views/dealers/new.html.erb
<%= content_for :title, "Nuevo distribuidor" %>
<% content_for :header_content do %>
<h1><b>Nuevo distribuidor</b></h1>
<% end %>
<%= render 'form' %>