config/routes.rb
Rails.application.routes.draw do

  get 'casos-de-exito' => 'static_pages#casos', as: 'casos'

  get 'contacto' => 'static_pages#contacto', as: 'contacto'

  get 'distribuidores' => 'static_pages#distribuidores', as: 'distribuidores'

  get 'comprar' => 'static_pages#comprar', as: 'comprar'
  post 'locate_me' => 'static_pages#locate_me'
  root 'static_pages#landing'

  post '/enviar_contacto' => 'static_pages#enviar_contacto', as: 'enviar_contacto'
  post '/enviar_distribuidor' => 'static_pages#enviar_distribuidor', as: 'enviar_distribuidor'

  get 'admin' => 'admin#index'
  scope 'admin', path_names: { new: 'nuevo', edit: 'editar' } do

    devise_for :users, :controllers => {:sessions => "sessions"} , path: "auth", path_names: { sign_in: 'login', sign_out: 'logout' }

    get 'contacto' => 'admin#contact', as: 'contact'
    patch 'contacto' => 'admin#contact'
    delete 'contacto' => 'admin#pref_del'

    get 'paypal' => 'admin#paypal', as: 'paypal'
    patch 'paypal' => 'admin#paypal'

    resources :users, path: 'usuarios', except: :show

    resources :announcements, path: 'anuncios', except: :show

    resources :cases, path: 'casos-de-exito'
    resources :dealers, path: 'distribuidores', except: :show

  end

end

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title) %></title>
  <meta name="viewport" content="initial-scale=1, maximum-scale=1">
  <%= stylesheet_link_tag 'admin', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'c4/c4', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href='http://fonts.googleapis.com/css?family=Lato:100,300,400,700' rel='stylesheet' type='text/css'>
  <%# Google maps api %>
</head>
<body data-no-turbolink='true' >

<% flash.each_with_index do |(key, value),i| %>
  <%= content_tag :div, class: "c4-flash #{key} animated slideInUp", style:"padding-bottom:#{i*50}px;z-index:#{1000-i};" do %>
    <div><%= value %></div>
  <% end %>
<% end %>


  <%#= color_palette() %>
  <% if user_signed_in? #NAV BAR %>
    <%= link_to admin_path , class: 'c4-home-button' do %>
      Batukeira
    <% end %>
    <div class="c4-menu-button">
      <span class="icon-menu"></span>
    </div>

    <div class="c4-nav">
      <div class="spacer"></div>
      <%= render '/navlinks' %>
    </div>
  <% end %>

  <div class="overlay"></div>
  <% if user_signed_in? #NAV BAR %>
    <div class="c4-header">
      <%= yield(:header_content) %>
    </div>
  <% end %>

  <div class="container <%= "animated fadeIn" if flash.empty? %>">
    <%= yield %>
  </div>

</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Batukeira</title>
  <meta name="viewport" content="initial-scale=1, maximum-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href='http://fonts.googleapis.com/css?family=Raleway:400,500,300' rel='stylesheet' type='text/css'>
  <script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-70758992-1', 'auto');
  ga('send', 'pageview');

</script>
</head>
<body class="animated fadeIn">
<% if Announcement.find_by(featured: true) %>
<div class="anuncio animated fadeInUp">
  <div class="close"></div>
  <a href="<%= Announcement.find_by(featured: true).link %>" style="background-image: url(<%= Announcement.find_by(featured: true).image.url %>)">
  </a>
</div>
<% end %>
<!-- <span class="ms-mq-test"></span> -->
<div class="menu-button"></div>
<nav class="nav-bar <%= yield(:fixed_nav) %>">
  <%= link_to 'Batukeira', root_path %>
  <%= link_to 'Comprar', comprar_path %>
  <%= link_to 'Casos de Éxito', casos_path %>
  <%= link_to 'Distribuir', distribuidores_path %>
  <%= link_to 'Contacto', contacto_path %>

</nav>

<div class="container-fitted">
    <%= yield %>
</div>
<div class="fondo"></div>

<section class="row disclaimer">
  <div class="row">
    <div class="texto">
      <div class="descripcion">
        Batukeira© by Shining Grace. All Rights Reserved

        Los resultados pueden variar según el individuo. La información proporcionada en este sitio web no pretende ser un consejo médico detallado y no es un sustituto para el tratamiento o diagnóstico de un profesional. Esta información no ha sido evaluada por Instituciones de Salud. Este producto no está destinado a tratar, diagnosticar, curar o prevenir ninguna enfermedad.
      </div>
    </div>
    <div class="contenedor-boton">

    </div>
  </div>
</section>


</body>
</html>